title: Study Buddy
description: An app for UHM ICS students to organize in-person study sessions in ICSpace.
show_downloads: false
theme: jekyll-theme-cayman

github:
  is_project_page: true
  owner: Study-Buddy-G2S6
  repository_url: https://github.com/Study-Buddy-G2S6/study-buddy